import express from "express";
import path from "path";
import cors from "cors";
import morgan from "morgan";
import home from "./routes/home";
const app = express();
app.set("view engine", "ejs");
app.set("views", path.join(__dirname, "../views"));
app.use(express.static(path.join(__dirname, '../public')));
app.use(cors());
app.use(morgan("dev"));
app.use(home);
export default app;
